/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud.ui;
import crud.client.GradeBook_Crud_client;
import crud.model.GradeBook;
import crud.util.Converter;
import java.net.URI;
import com.sun.jersey.api.client.ClientResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import javax.swing.JFrame;
import javax.ws.rs.core.Response;
import javax.xml.bind.JAXBException;

/**
 *
 * @author SAHIL
 */
public class GradeBook_UI extends javax.swing.JFrame {

    /**
     * Creates new form GradeBook_UI
     */
   private static final Logger LOG = LoggerFactory.getLogger(GradeBook_UI.class);
    
    private GradeBook_Crud_client gradebookClient;
    
    private URI resourceURI;
    public GradeBook_UI() {
        
    initComponents();
        
        gradebookClient = new GradeBook_Crud_client();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        mediaType = new javax.swing.JTextField();
        taskID = new javax.swing.JTextField();
        grades = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        statusCode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        createRadio = new javax.swing.JRadioButton();
        readRadio = new javax.swing.JRadioButton();
        updateRadio = new javax.swing.JRadioButton();
        deleteRadio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        location = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        feedBack = new javax.swing.JTextField();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        studentName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        statusInfo = new javax.swing.JTextField();
        appeal = new javax.swing.JRadioButton();
        appealCheck = new javax.swing.JCheckBox();
        workItem = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("Grades");

        mediaType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediaTypeActionPerformed(evt);
            }
        });

        taskID.setEnabled(false);
        taskID.setName("IdField"); // NOI18N
        taskID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskIDActionPerformed(evt);
            }
        });

        grades.setName("PriorityField"); // NOI18N
        grades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradesActionPerformed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("HTTP Status Code");

        statusCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusCodeActionPerformed(evt);
            }
        });

        jLabel7.setText("Location");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setText("HTTP Header Info");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Action");

        buttonGroup2.add(createRadio);
        createRadio.setSelected(true);
        createRadio.setText("Create");
        createRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRadioActionPerformed(evt);
            }
        });

        buttonGroup2.add(readRadio);
        readRadio.setText("Read");
        readRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readRadioActionPerformed(evt);
            }
        });

        buttonGroup2.add(updateRadio);
        updateRadio.setText("Update");
        updateRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRadioActionPerformed(evt);
            }
        });

        buttonGroup2.add(deleteRadio);
        deleteRadio.setText("Delete");
        deleteRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRadioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("GradeBook Values");

        jLabel3.setText("Student ID");

        location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationActionPerformed(evt);
            }
        });

        jLabel4.setText("Work Item");

        jLabel9.setText("Media Type");

        jLabel10.setText("FeedBack");

        feedBack.setName("PriorityField"); // NOI18N
        feedBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedBackActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setSelected(true);
        jRadioButton5.setText("Instructor");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("Student");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jLabel11.setText("Student Name");

        studentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentNameActionPerformed(evt);
            }
        });

        jLabel12.setText("Status Info");

        statusInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusInfoActionPerformed(evt);
            }
        });

        buttonGroup2.add(appeal);
        appeal.setText("Appeal");
        appeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appealActionPerformed(evt);
            }
        });

        appealCheck.setText("Request Appeal");
        appealCheck.setEnabled(false);
        appealCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appealCheckActionPerformed(evt);
            }
        });

        workItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quiz", "Midterm", "assignment" }));
        workItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createRadio)
                        .addGap(83, 83, 83)
                        .addComponent(readRadio)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(updateRadio))
                            .addComponent(jLabel1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(appealCheck)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(taskID, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(grades, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(feedBack, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel11)
                                    .addComponent(studentName))
                                .addComponent(workItem, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(jRadioButton6)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(statusCode, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addGap(247, 315, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mediaType, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(statusInfo)
                                            .addComponent(location)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel12))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addContainerGap())))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(deleteRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)
                                        .addComponent(appeal)))
                                .addGap(68, 68, 68))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteRadio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(createRadio)
                        .addComponent(readRadio)
                        .addComponent(updateRadio)
                        .addComponent(appeal)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jButton1)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(taskID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(workItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel10)
                                .addGap(8, 8, 8)
                                .addComponent(feedBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addGap(2, 2, 2)
                                .addComponent(mediaType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(appealCheck)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mediaTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediaTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mediaTypeActionPerformed

    private void taskIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taskIDActionPerformed

    private void gradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradesActionPerformed
private void populateFormDelete(ClientResponse clientResponse){
                
        taskID.setText("");
        workItem.setSelectedIndex(0);
        grades.setText("");
        
        statusCode.setText(Integer.toString(clientResponse.getStatus()));
        location.setText("");
        mediaType.setText("");
        
        statusInfo.setText(clientResponse.getStatusInfo().toString());
    }
private String formToXMLString(){
        GradeBook gradeBook = new GradeBook();
        if (!taskID.getText().equals("")){
            gradeBook.setTaskId(Integer.parseInt(taskID.getText()));
        }
        gradeBook.setStudentName(studentName.getText());
        gradeBook.setworkItem(workItem.getItemAt(workItem.getSelectedIndex()));
        gradeBook.setGrades((grades.getText()));
        gradeBook.setfeedBack((feedBack.getText()));
        if(appeal.isSelected())
            gradeBook.setAppeal(true);
        else
            gradeBook.setAppeal(false);
        String xmlString = Converter.convertFromObjectToXml(gradeBook, gradeBook.getClass());
        
        return xmlString;
    }    

    private void populateForm(ClientResponse clientResponse){
         String entity=clientResponse.getEntity(String.class);
       
         try{
            if ((clientResponse.getStatus() == Response.Status.OK.getStatusCode()) ||
                (clientResponse.getStatus() == Response.Status.CREATED.getStatusCode())){
                
                GradeBook gradebook = (GradeBook)Converter.convertFromXmlToObject(entity, GradeBook.class);          
                
                taskID.setText(Integer.toString(gradebook.getTaskId()));
                studentName.setText(gradebook.getStudentName());
                switch(gradebook.getworkItem()){
                    case "Quiz": {
                            workItem.setSelectedIndex(0);
                            break;
                        }
                    case "Midterm":{
                            workItem.setSelectedIndex(1);
                            break;
                    }
                    case "assignment":{
                        workItem.setSelectedIndex(2);
                            break;
                    }
                    
                }
                grades.setText((gradebook.getGrades()));
                feedBack.setText(gradebook.getfeedBack());
                if(gradebook.getAppeal()==true)
                    appealCheck.setSelected(true);
                else
                    appealCheck.setSelected(false);
            } else {
                
                studentName.setText("");
                workItem.setSelectedIndex(0);
                grades.setText("");
                feedBack.setText("");
            }            
            
            statusCode.setText(Integer.toString(clientResponse.getStatus()));
            mediaType.setText(clientResponse.getType().toString());
            statusInfo.setText(clientResponse.getStatusInfo().toString());         
            if (clientResponse.getStatus() == Response.Status.CREATED.getStatusCode()){
                location.setText(clientResponse.getLocation().toString());
            } else {
                location.setText("");
            }
            
        } catch (JAXBException e){
            e.printStackTrace();
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                                    
        
        String taskId = taskID.getText();
        String workItem=this.workItem.getItemAt(this.workItem.getSelectedIndex());
        if (createRadio.isSelected()){
            
            ClientResponse clientResponse = gradebookClient.createGrades(this.formToXMLString());
            
            //taskID.setText("");
            
            
            
            resourceURI = clientResponse.getLocation();
            statusInfo.setText(clientResponse.getStatusInfo().toString());
            this.populateForm(clientResponse);
        } else if (readRadio.isSelected()) {
        
            
            ClientResponse clientResponse = gradebookClient.readGrades(ClientResponse.class, taskId,workItem);
           
            this.populateForm(clientResponse);  
        } else if (updateRadio.isSelected()) {
            
            
            
            ClientResponse clientResponse = gradebookClient.updateGrades(this.formToXMLString(), taskId,workItem);
            
            this.populateForm(clientResponse);
        } else if (deleteRadio.isSelected()) {
            
            
            ClientResponse clientResponse = gradebookClient.deleteGrades(taskId,workItem);
            this.populateFormDelete(clientResponse);
        }   
            else if(appeal.isSelected()){               //appeal               
                ClientResponse clientResponse = gradebookClient.updateAppeal(this.formToXMLString(), taskId,workItem);            
                this.populateForm(clientResponse);                    
            }
        
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void statusCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusCodeActionPerformed

    private void createRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRadioActionPerformed
            taskID.setEnabled(false);
            
            studentName.setEnabled(true);
            workItem.setEnabled(true);
            grades.setEnabled(true);
            feedBack.setEnabled(true);
            appeal.setEnabled(false);
            
        
        taskID.setText("");
        studentName.setText("");
        workItem.setSelectedIndex(0);
        grades.setText("");
        feedBack.setText("");
        statusCode.setText("");
        location.setText("");
        mediaType.setText("");
        statusInfo.setText("");
        
    }//GEN-LAST:event_createRadioActionPerformed

    private void readRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readRadioActionPerformed
        
        
        taskID.setEnabled(true);
            
        studentName.setEnabled(false);
        workItem.setEnabled(true);
        grades.setEnabled(false);
        feedBack.setEnabled(false);
           
        taskID.setText("");
        studentName.setText("");
        workItem.setSelectedIndex(0);
        grades.setText("");
        feedBack.setText("");
        statusCode.setText("");
        location.setText("");
        mediaType.setText("");
        statusInfo.setText("");
    }//GEN-LAST:event_readRadioActionPerformed

    private void updateRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRadioActionPerformed
       // LOG.info("Selecting radio button {}", updateRadio.getText());
      //  createRadio.setSelected(false);
      //  readRadio.setSelected(false);
      //  deleteRadio.setSelected(false);
        taskID.setEnabled(true);
            statusInfo.setText("");
            studentName.setEnabled(true);
            workItem.setEnabled(true);
            grades.setEnabled(true);
            feedBack.setEnabled(true);
            
            taskID.setText("");
        studentName.setText("");
        workItem.setSelectedIndex(0);
        grades.setText("");
        feedBack.setText("");
        statusCode.setText("");
        location.setText("");
        mediaType.setText("");
       
    }//GEN-LAST:event_updateRadioActionPerformed

    private void deleteRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRadioActionPerformed
     //   LOG.info("Selecting radio button {}", deleteRadio.getText());
     //   createRadio.setSelected(false);
     //   readRadio.setSelected(false);
     //   updateRadio.setSelected(false);
        taskID.setEnabled(true);
            
            studentName.setEnabled(false);
            workItem.setEnabled(true);
            grades.setEnabled(false);
            feedBack.setEnabled(false);
            
            taskID.setText("");
        studentName.setText("");
        workItem.setSelectedIndex(0);
        grades.setText("");
        feedBack.setText("");
        statusCode.setText("");
        location.setText("");
        mediaType.setText("");
        statusInfo.setText("");
            
    }//GEN-LAST:event_deleteRadioActionPerformed

    private void locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationActionPerformed

    private void feedBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feedBackActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        readRadio.setEnabled(true);
        readRadio.setSelected(false);
        createRadio.setEnabled(true);
        createRadio.setSelected(true);
        updateRadio.setEnabled(true);
        updateRadio.setSelected(false);
        deleteRadio.setEnabled(true);
        deleteRadio.setSelected(false);
        appeal.setEnabled(false);
        appeal.setSelected(false);
        
//        taskID.setText("");
//        studentName.setText("");
//        workItem.setText("");
//        grades.setText("");
//        feedBack.setText("");
//        statusCode.setText("");
//        location.setText("");
//        mediaType.setText("");
//        statusInfo.setText("");


          taskID.setEnabled(false);
            
            studentName.setEnabled(true);
            workItem.setEnabled(true);
            grades.setEnabled(true);
            feedBack.setEnabled(true);
            appealCheck.setEnabled(false);
        
        taskID.setText("");
        studentName.setText("");
        workItem.setSelectedIndex(0);
        grades.setText("");
        feedBack.setText("");
        statusCode.setText("");
        location.setText("");
        mediaType.setText("");
        statusInfo.setText("");
        createRadio.setSelected(true);

    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        createRadio.setEnabled(false);
        updateRadio.setEnabled(false);
        deleteRadio.setEnabled(false);
        readRadio.setEnabled(true);
        readRadio.setSelected(true);
        createRadio.setSelected(false);
        updateRadio.setSelected(false);
        deleteRadio.setSelected(false);
        appeal.setSelected(false);
        appeal.setEnabled(true);
        taskID.setEnabled(true);
        studentName.setEnabled(false);
            workItem.setEnabled(false);
            grades.setEnabled(false);
            feedBack.setEnabled(false);
        taskID.setText("");
        
        statusInfo.setText("");
        studentName.setText("");
        workItem.setSelectedIndex(0);
        grades.setText("");
        feedBack.setText("");
        statusCode.setText("");
        location.setText("");
        mediaType.setText("");

    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void studentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentNameActionPerformed

    private void statusInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusInfoActionPerformed

    private void appealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appealActionPerformed
        // TODO add your handling code here:
        
        createRadio.setEnabled(false);
        updateRadio.setEnabled(false);
        deleteRadio.setEnabled(false);
        readRadio.setEnabled(true);
        readRadio.setSelected(false);
        createRadio.setSelected(false);
        updateRadio.setSelected(false);
        deleteRadio.setSelected(false);
        appeal.setSelected(false);
        appeal.setEnabled(true);
        studentName.setEnabled(false);
        workItem.setEnabled(true);
        grades.setEnabled(false);
        feedBack.setEnabled(false);
        taskID.setText("");
        statusInfo.setText("");
        studentName.setText("");
        workItem.setSelectedIndex(0);
        grades.setText("");
        feedBack.setText("");
        statusCode.setText("");
        location.setText("");
        mediaType.setText("");
        
    }//GEN-LAST:event_appealActionPerformed

    private void appealCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appealCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appealCheckActionPerformed

    private void workItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workItemActionPerformed
        // TODO add your handling code here:
        System.out.println("cmobobox value is "+workItem.getSelectedIndex());
    }//GEN-LAST:event_workItemActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradeBook_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradeBook_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradeBook_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradeBook_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradeBook_UI().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton appeal;
    private javax.swing.JCheckBox appealCheck;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton createRadio;
    private javax.swing.JRadioButton deleteRadio;
    private javax.swing.JTextField feedBack;
    private javax.swing.JTextField grades;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JTextField location;
    private javax.swing.JTextField mediaType;
    private javax.swing.JRadioButton readRadio;
    private javax.swing.JTextField statusCode;
    private javax.swing.JTextField statusInfo;
    private javax.swing.JTextField studentName;
    private javax.swing.JTextField taskID;
    private javax.swing.JRadioButton updateRadio;
    private javax.swing.JComboBox<String> workItem;
    // End of variables declaration//GEN-END:variables
}
